disabled_rules:
- shorthand_operator
- todo
- trailing_whitespace

opt_in_rules:
- force_unwrapping

excluded:
- traveline/Sources/App/AppDelegate.swift
- traveline/Sources/App/SceneDelegate.swift
- "Tuist"
- "Plugins"

nesting:
  type_level:
    warning: 2

line_length:
  warning: 150

identifier_name:
    min_length:
        warning: 1
